// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) error
	GetAllJobs(ctx context.Context) ([]Job, error)
	GetJobsByStatus(ctx context.Context, status JobStatus) ([]Job, error)
	GetPendingJobs(ctx context.Context) ([]GetPendingJobsRow, error)
	GetPollingInterval(ctx context.Context) (int32, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) error
}

var _ Querier = (*Queries)(nil)
